services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: code-reviewer-backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    volumes:
      - sqlite-data:/app/db/data
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: code-reviewer-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

volumes:
  sqlite-data:

networks:
  app-network:
    driver: bridge